apiVersion: store.test.keptn.sh/v1
kind: Book
metadata:
  labels:
    app.kubernetes.io/name: book
    app.kubernetes.io/instance: book-sample
    app.kubernetes.io/part-of: crd-scenarios
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crd-scenarios
  name: book-sample
spec:
  # TODO(user): Add fields here
